### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'module'

### ISSUE THREAD

**Issue by wangsen-zy** [zhunzhong07/HHL#13]
Hi, when I run stargan4reid myself and try to generate CamStyle imgaes, a bug appeared.The following is the specific content of the bug：

Start training...
Elapsed [0:00:05], Iteration [1/6], D/loss_real: 0.0386, D/loss_fake: -0.0519, D/loss_cls: 1.7772, D/loss_gp: 10.2668, G/loss_fake: 0.0517, G/loss_rec: 0.4263, G/loss_cls: 1.6729
Traceback (most recent call last):
  File "/home/wss/HHL/HHL-master/stargan4reid/main.py", line 95, in <module>
    main(config)
  File "/home/wss/HHL/HHL-master/stargan4reid/main.py", line 36, in main
    solver.train()
  File "/home/wss/HHL/HHL-master/stargan4reid/solver.py", line 328, in train
    torch.save(self.G.module.state_dict(), G_path)
  File "/home/wss/anaconda3/envs/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
**AttributeError: 'Generator' object has no attribute 'module'**
Saved real and fake images into ./market/samples/1-images.jpg...

My operating environment is torch-cpu-0.4.0, and torchvision 0.2.1, the program is running under python3.6.
I tried running under pytorch- cpu-1.1.0, but nothing can help.
Hoping to get your reply, and good luck.

**Comment by wangsen-zy** [comment]
OK, I solved that.
It seems that the author did not expect someone to use the CPU for experiments when writing the code, just as I did not expect the COVID-19 virus.
Here are my solutions：
![image](https://user-images.githubusercontent.com/53846882/76589711-e8abf400-6525-11ea-92c6-bff36b24a765.png)
  U just need to add the data into the device, and that's all you need to do.
